#日期显示的格式
#yyyy：年
#MM：月
#dd：日
#hh：1~12小时制(1-12)
#HH：24小时制(0-23)
#mm：分
#ss：秒
#S：毫秒
#E：星期几
#D：一年中的第几天
#F：一月中的第几个星期(会把这个月总共过的天数除以7)
#w：一年中的第几个星期
#W：一月中的第几星期(会根据实际情况来算)
#a：上下午标识
#k：和HH差不多，表示一天24小时制(1-24)。
#K：和hh差不多，表示一天12小时制(0-11)。
#z：表示时区
date_format: 'yyyy年MM月dd日 HH:mm:ss'
#数据库配置信息
database:
  #使用数据库的类型,可选:SQLite、Mysql
  type: 'SQLite'
  #如果为SQLite这一项可以无视
  #数据库名
  schema: 'bluefriends'
  #数据库地址,如果是Mysql需要包括端口,如:127.0.0.1:3306
  #如果是SQLite,会自动将%local%占位符替换为插件配置文件夹(BlueFriends)路径
  url: '%local%data.db'
  #如果为SQLite这一项可以无视
  #用户名
  user: 'root'
  #如果为SQLite这一项可以无视
  #密码
  password: 'root'
  #储存玩家信息的表名
  #不建议修改
  individual_table: 'individual'
  #储存邮件信息的表名
  #不建议修改
  mail_table: 'mail'
#GUI-IDCard
#个人信息的显示界面配置选项==============->
#身份证的默认信息
idcard:
  default:
    #头像图片地址
    #玩家还没有设置个性头像会使用此图片作为头像
    headurl: '[local]img#4.png'
    #默认头像边框
    headborderurl: '[local]img#3.png'
    #真实姓名
    realname: '保密'
    #生日
    birthday: '保密'
    #性别
    sex: '保密'
    #住址
    address: '保密'
    #qq
    qq: '保密'
    #游戏
    email: '保密'
    #默认的个性签名
    signature: '该玩家没有任何个性签名'
hub:
  url: '[local]hub#1.png'
  x: 0
  y: 0
  w: 200
  h: 35
  contents_x: 20
  contents_y: 10
  time: 8
#是否开启好友上线提示
join_msg: true
online_format: '&a●在线'
offline_format: '&8●离线'
system_format: '&c系统'
read_format: '&8已读'
unread_format: '&a未读'


